### ISSUE TITLE
CORS 로 인한 API 호출 불가

### ISSUE THREAD

**Issue by namuuCY** [ASAC-06-Team-C/reddit-backend#27]
# 문제 상황

FE : Vite는 Dev용 서버를 localhost:5173에서,
BE : Spring Boot는 tomcat의 서버를 localhost:8080 에서 사용하기 때문에
port가 달라 CORS 이슈 발생

# 해결 방법

**Comment by daejin94** [comment]
https://github.com/ASAC-06-Team-C/reddit-backend/commit/888c4eebe70001cf8a5693801500ca16ac479b7b

config 파일 추가 후 이슈 해결 완료
